# Generated by Django 3.0.7 on 2020-06-19 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CATMain_Category',
            new_name='CATName',
        ),
    ]
