# Generated by Django 3.0.7 on 2020-06-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200619_0325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Accessories',
        ),
    ]
