# Generated by Django 3.0.7 on 2020-06-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_prdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDescountPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount Price'),
            preserve_default=False,
        ),
    ]
